### ISSUE TITLE
登陆困难，且常常进不了主界面

### ISSUE THREAD

**Issue by huangyy126** [Pawdroid/FoxoVPN#1]
电脑版登陆困难，常常进不了主界面。而且每次登陆都得输入账号密码，没有自动登录进入主界面的设置。偶尔登陆成功一次进入主界面，只要退出主界面，再想进入主界面非常困难（系统是Windows 10 家庭中文版21H1），自己尝试如下解决办法：https://cdn.159236.xyz/#/home——注销，再登陆 （或每次不用时，设置——注销登录），但还是出现登陆进不去主界面的情况，希望是打开软件时，软件会自动进行账号登录，并且用户随时都能打开主界面方便用户进行设置

**Comment by Pawdroid** [comment]
正常来说是再次打开客户端是会自动登陆的，如果无法自动登陆，手动登陆又没有反应的话，应该是网络问题，需要打开其他软件的代理进行登录。另外我们也在优化登录流程，新版本会让用户在不登陆的情况下使用免费节点，如果想使用更多节点的话则需要登陆。
