### ISSUE TITLE
获取最新配置看不到节点

### ISSUE THREAD

**Issue by jk9527** [Pawdroid/FoxoVPN#2]
前几天使用正常，今天更新最新节点后看不到节点，查看运行时配置可以看到下载成功，点击重新激活配置仍然看不到节点，再次查看运行时配置已经被清空，重启软件也不行。软件卸载重装也不行，版本1.2.3，系统mac os 10.15.7 。使用验证码更新时提示验证码已过期

**Comment by jk9527** [comment]
刚试了下更新又自动恢复了，可以用了

**Comment by stephen-cusi** [comment]
> 刚试了下更新又自动恢复了，可以用了

好长时间没用了 `速度怎么样`

**Comment by jk9527** [comment]
> > 刚试了下更新又自动恢复了，可以用了
> 
> 好长时间没用了 `速度怎么样`

速度对我来说不重要，能通能上github拉代码就行

**Comment by stephen-cusi** [comment]
> > > 刚试了下更新又自动恢复了，可以用了
> > 
> > 
> > 好长时间没用了 `速度怎么样`
> 
> 速度对我来说不重要，能通能上github拉代码就行

差不多1mb/s吧 有时候还会拉挂🥸
